version: '3.7'
services:
  db:
    image: postgres:9.6.12
    container_name: cpm_db
    hostname: pg_server
    restart: always
    ports:
      - "54321:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ge_apm:/var/lib/postgresql/data
      - /home/nick/data:/root/data

networks:
  backend:
    
volumes:
  ge_apm:
    name: rcc_cpm

