version: '3.7'
services:
  dw_db:
    image: mysql:5.6.39
    container_name: dw_mysql
    hostname: dw_server
    restart: always
    ports:
      - 33061:3306
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: serphydose
      MYSQL_USER: serphydose
      MYSQL_PASSWORD: Stra67000
    volumes:
      #- ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      #- ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - mysql_data:/var/lib/mysql
      - mysql_log:/var/log/mysql
      - /home/nick/data:/root/data

networks:
  backend:

volumes:
  mysql_data:
    name: mysql_data
  mysql_log:
    name: mysql_log

