version: '3.7'
services:
  maria_db:
    image: mariadb:10.4.12
    container_name: mariadb
    hostname: mariadb_server
    restart: always
    ports:
      - 33081:3306
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TimeZone: "Asia/Shanghai"
    volumes:
      # 容器与宿主机时间同步
      - /etc/localtime:/etc/localtime
      - mariadb_data:/var/lib/mysql
      - /home/nick/data:/root/data

networks:
  backend:

volumes:
  mariadb_data:
    name: mariadb_data

