version: '3.7'
services:
  pg_10:
    image: postgres:10.10
    container_name: rcc_db
    hostname: pg_server
    restart: always
    ports:
      - "54322:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pg10:/var/lib/postgresql/data
      - /home/nick/data:/root/data

networks:
  backend:
    
volumes:
  pg10:
    name: pg_10

